'use strict';
const $=id=>document.getElementById(id),N=256*256,MODELS=[['fixed','Fixed head'],['conditioned','Q-conditioned'],['ensemble','Deep ensemble'],['mc','MC dropout']];
let current=0,example=null,busy=false,point={x:128,y:128};const cache=new Map();
function bytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function decode(s){const b=bytes(s),v=new DataView(b.buffer);if(DATASET.encoding==='float32'){const out=new Float32Array(b.length/4);for(let i=0;i<out.length;i++)out[i]=v.getFloat32(i*4,true);return out}const out=new Float32Array(b.length/2);for(let i=0;i<out.length;i++){const h=v.getUint16(i*2,true),sign=h&32768?-1:1,e=(h>>10)&31,f=h&1023;out[i]=sign*(e===0?2**-14*f/1024:e===31?(f?NaN:Infinity):2**(e-15)*(1+f/1024))}return out}
window.receiveExample=(i,d)=>{d.measurement=bytes(d.measurement);d.target=bytes(d.target);for(const m of Object.values(d.models)){m.mean=decode(m.mean);m.width=decode(m.width);if(m.widthRGB)m.widthRGB=decode(m.widthRGB);m.error=new Float32Array(N);for(let p=0;p<N;p++)for(let c=0;c<3;c++)m.error[p]+=Math.abs(m.mean[c*N+p]-d.target[c*N+p]/255)/3;delete m.q;delete m.endpoints}cache.set(i,d);while(cache.size>3)cache.delete(cache.keys().next().value)};
function lock(value){busy=value;for(const id of ['example','previous','next','random'])$(id).disabled=value}
function load(i){if(busy)return;lock(true);$('status').textContent='Loading saved inference…';const finish=()=>{example=cache.get(i);current=i;$('example').value=i;render();$('status').textContent=`${i+1} / ${DATASET.count} · image ${example.id}`;lock(false)};if(cache.has(i)){finish();return}const s=document.createElement('script');s.src=`${window.DATA_PATH||'data'}/example_${String(i).padStart(2,'0')}.js`;const fail=()=>{s.remove();$('status').textContent='Could not load this example. Keep the data folder beside the HTML file.';lock(false)};s.onload=()=>{s.remove();cache.has(i)?finish():fail()};s.onerror=fail;document.body.append(s)}
const stops=[[8,13,36],[48,54,154],[188,69,146],[250,159,105],[255,243,188]];
const maxValue=()=>DATASET.mapMax||Math.max(DATASET.widthMax,DATASET.errorMax);
function color(value){const t=Math.max(0,Math.min(1,value/maxValue()))*4,k=Math.min(3,Math.floor(t)),a=t-k;return stops[k].map((v,c)=>Math.round(v*(1-a)+stops[k+1][c]*a))}
function draw(cv,data,type){const ctx=cv.getContext('2d'),im=ctx.createImageData(256,256);for(let p=0;p<N;p++){const rgb=type==='map'?color(data[p]):[0,1,2].map(c=>Math.max(0,Math.min(255,data[c*N+p]*(type==='byte'?1:255))));for(let c=0;c<3;c++)im.data[4*p+c]=rgb[c];im.data[4*p+3]=255}const z=Number($('zoom').value),size=256/z,ox=Math.max(0,Math.min(256-size,point.x-size/2)),oy=Math.max(0,Math.min(256-size,point.y-size/2));Object.assign(cv.dataset,{ox,oy,size});const tmp=document.createElement('canvas');tmp.width=tmp.height=256;tmp.getContext('2d').putImageData(im,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,ox,oy,size,size,0,0,256,256);const x=(point.x-ox+.5)*z,y=(point.y-oy+.5)*z;for(const [stroke,width]of [['black',3],['white',1]]){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x-4,y);ctx.lineTo(x+4,y);ctx.moveTo(x,y-4);ctx.lineTo(x,y+4);ctx.stroke()}}
function render(){if(!example)return;draw($('measurement'),example.measurement,'byte');draw($('target'),example.target,'byte');for(const [key]of MODELS){const m=example.models[key];draw($(key+'-prediction'),m.mean,'float');draw($(key+'-error'),m.error,'map');draw($(key+'-width'),m.width,'map');const v=m.metrics;$(key+'-metrics').innerHTML=[['PSNR',v.psnr.toFixed(3)+' dB'],['SSIM',v.ssim.toPrecision(5)],['Coverage',(v.coverage*100).toFixed(2)+'%'],['Mean |error|',(m.error.reduce((a,b)=>a+b,0)/N).toFixed(5)],['Mean width',v.width.toFixed(5)]].map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('')}inspect()}
function inspect(){if(!example)return;const p=point.y*256+point.x,channel=$('channel').value,channels=channel==='rgb'?[0,1,2]:[Number(channel)],avg=a=>channels.reduce((sum,c)=>sum+a[c*N+p],0)/channels.length;const gt=channels.reduce((s,c)=>s+example.target[c*N+p]/255,0)/channels.length;$('pixelTitle').textContent=`Selected pixel (${point.x}, ${point.y})`;$('pixelTruth').textContent=`Ground truth ${gt.toFixed(5)} · ${channel==='rgb'?'RGB average':$('channel').selectedOptions[0].textContent}`;$('pixelRows').innerHTML=MODELS.map(([k,label])=>{const m=example.models[k],error=channels.reduce((s,c)=>s+Math.abs(m.mean[c*N+p]-example.target[c*N+p]/255),0)/channels.length,width=m.widthRGB?avg(m.widthRGB):channel==='rgb'?m.width[p]:null;return `<tr><td>${label}</td><td>${avg(m.mean).toFixed(5)}</td><td>${error.toFixed(5)}</td><td>${width===null?'Unavailable per channel in legacy data':width.toFixed(5)}</td></tr>`}).join('')}
function pick(x,y){point={x:Math.max(0,Math.min(255,x)),y:Math.max(0,Math.min(255,y))};render()}
function boot(){if(!window.DATASET){$('status').textContent='Inference data not yet available.';return}const legacy=!DATASET.study;$('provenance').textContent=legacy?'LAYOUT PREVIEW · Older 20k-training RML experiment, backbone 50 / fixed head 50. These are not the new 60k-training final results.':`${DATASET.study} · ${DATASET.trainCount.toLocaleString()} training images · backbone epoch ${DATASET.epoch} · fixed head ${DATASET.headEpochs} epochs · ${DATASET.calibrationMethod||'Empirical'} calibration, target 90%`;$('settings').textContent=DATASET.notes;$('camera').value=window.CAMERA||'rml';$('camera').onchange=e=>{location.search='?camera='+encodeURIComponent(e.target.value)};$('maximum').textContent=maxValue().toFixed(4)+' · high';$('example').innerHTML=DATASET.ids.map((id,i)=>`<option value="${i}">${i+1} · image ${id}</option>`).join('');let html='<div></div>'+MODELS.map(([k,label])=>`<div class="model-head"><h2>${label}</h2><p>${k==='ensemble'?'Five trained members':k==='mc'?'30 stochastic passes':k==='fixed'?'Frozen backbone + interval head':'Quantile-conditioned intervals'}</p></div>`).join('');for(const [key,label,sub]of [['prediction','Reconstruction','Model prediction'],['error','Absolute error','|GT − reconstruction|'],['width','Uncertainty','UB − LB']])html+=`<div class="row-label">${label}<small>${sub}</small></div>`+MODELS.map(([k,l])=>`<canvas id="${k}-${key}" width="256" height="256" tabindex="0" aria-label="${l}: ${label}"></canvas>`).join('');html+='<div class="row-label">This image<small>Unclipped metrics</small></div>'+MODELS.map(([k])=>`<div class="metrics" id="${k}-metrics"></div>`).join('');$('matrix').innerHTML=html;for(const cv of document.querySelectorAll('canvas')){cv.tabIndex=0;cv.onclick=e=>{if(busy)return;const b=cv.getBoundingClientRect();pick(Math.floor(Number(cv.dataset.ox)+(e.clientX-b.left)/b.width*Number(cv.dataset.size)),Math.floor(Number(cv.dataset.oy)+(e.clientY-b.top)/b.height*Number(cv.dataset.size)))};cv.onkeydown=e=>{const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(d){e.preventDefault();pick(point.x+d[0],point.y+d[1])}}}$('example').onchange=e=>load(Number(e.target.value));$('next').onclick=()=>load((current+1)%DATASET.count);$('previous').onclick=()=>load((current+DATASET.count-1)%DATASET.count);$('random').onclick=()=>load((current+1+Math.floor(Math.random()*(DATASET.count-1)))%DATASET.count);$('zoom').onchange=render;$('channel').onchange=inspect;load(0);if(window.renderLearningCurves)renderLearningCurves()}boot();
