'use strict';
const $=id=>document.getElementById(id),M=[['fixed','Fixed head','#eac879','50 backbone + 50 head epochs'],['conditioned','Q-conditioned','#90edc0','50 epochs · direct quantile queries'],['ensemble','Deep ensemble','#90b9ff','5 members × 50 epochs · Gaussian mixture'],['mc','MC dropout','#de9bef','50 epochs · 30 stochastic draws']];
const N=256*256;let current=0,example=null,point={x:128,y:128},busy=false;const cache=new Map();
function bytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}function half(s){const b=bytes(s),v=new DataView(b.buffer),out=new Float32Array(b.length/2);for(let i=0;i<out.length;i++){let h=v.getUint16(i*2,true),sign=h&32768?-1:1,e=(h>>10)&31,f=h&1023;out[i]=sign*(e===0?2**-14*(f/1024):e===31?(f?NaN:Infinity):2**(e-15)*(1+f/1024))}return out}
function lock(v){busy=v;for(const id of ['previous','next','random','example'])$(id).disabled=v}
window.receiveExample=(i,d)=>{d.measurement=bytes(d.measurement);d.target=bytes(d.target);for(const m of Object.values(d.models)){m.mean=half(m.mean);m.width=half(m.width);if(m.q)m.q=half(m.q);if(m.endpoints)m.endpoints=half(m.endpoints)}cache.set(i,d);while(cache.size>3)cache.delete(cache.keys().next().value)};
function load(i){if(busy)return;lock(true);$('status').textContent='Loading saved model responses…';const finish=()=>{current=i;example=cache.get(i);$('example').value=i;render();$('status').textContent=`Example ${i+1} / ${DATASET.count} · image ${example.id}`;lock(false)};if(cache.has(i)){finish();return}const s=document.createElement('script');s.src=`data/example_${String(i).padStart(2,'0')}.js`;s.onload=()=>{s.remove();if(cache.has(i))finish();else fail()};const fail=()=>{$('status').textContent='Could not load example. Keep the data folder beside index.html.';lock(false)};s.onerror=()=>{s.remove();fail()};document.body.append(s)}
const stops=[[8,13,36],[48,54,154],[188,69,146],[250,159,105],[255,243,188]];
function color(v,max){let t=Math.max(0,Math.min(1,v/max))*4,k=Math.min(3,Math.floor(t)),a=t-k;return stops[k].map((x,c)=>Math.round(x*(1-a)+stops[k+1][c]*a))}
function draw(canvas,data,type,max){const ctx=canvas.getContext('2d'),im=ctx.createImageData(256,256);if(!data){ctx.fillStyle='#17202b';ctx.fillRect(0,0,256,256);ctx.fillStyle='#a0aec0';ctx.font='14px system-ui';ctx.textAlign='center';ctx.fillText('Not predicted by this head',128,120);ctx.font='11px system-ui';ctx.fillText('Native outputs: q .025 / .975',128,144);return}for(let p=0;p<N;p++){let rgb=type==='map'?color(data[p],max):[0,1,2].map(c=>Math.max(0,Math.min(255,data[c*N+p]*(type==='byte'?1:255))));for(let c=0;c<3;c++)im.data[p*4+c]=rgb[c];im.data[p*4+3]=255}let z=Number($('zoom').value),size=256/z,ox=Math.max(0,Math.min(256-size,point.x-size/2)),oy=Math.max(0,Math.min(256-size,point.y-size/2));canvas.dataset.ox=ox;canvas.dataset.oy=oy;canvas.dataset.size=size;const tmp=document.createElement('canvas');tmp.width=tmp.height=256;tmp.getContext('2d').putImageData(im,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,ox,oy,size,size,0,0,256,256);const cx=(point.x-ox+.5)*z,cy=(point.y-oy+.5)*z;function cross(){ctx.beginPath();ctx.moveTo(cx-5,cy);ctx.lineTo(cx+5,cy);ctx.moveTo(cx,cy-5);ctx.lineTo(cx,cy+5);ctx.stroke()}ctx.strokeStyle='#000';ctx.lineWidth=3;cross();ctx.strokeStyle='#fff';ctx.lineWidth=1;cross()}
function quantileImage(key,j){let m=example.models[key];if(key!=='fixed')return m.q.subarray(j*3*N,(j+1)*3*N);if(!$('approx').checked)return null;const a=new Float32Array(3*N),t=(DATASET.quantiles[j]-.025)/.95;for(let p=0;p<3*N;p++)a[p]=m.endpoints[p]+t*(m.endpoints[3*N+p]-m.endpoints[p]);return a}
function shownImage(key){return $('imageMode').value==='mean'?example.models[key].mean:quantileImage(key,Number($('imageMode').value))}
function render(){if(!example)return;draw($('measurement'),example.measurement,'byte');draw($('target'),example.target,'byte');const mode=$('imageMode').value,reference=$('difference').value,ref=reference==='target'?null:shownImage(reference);for(const [key]of M){let m=example.models[key],shown=shownImage(key);draw($(key+'-prediction'),shown,'float');$(key+'-imageLabel').textContent=mode==='mean'?'Reconstruction':`q = ${DATASET.quantiles[Number(mode)].toFixed(2)}${key==='fixed'?($('approx').checked?' · assumed interpolation':' · unavailable'):''}`;draw($(key+'-width'),m.width,'map',DATASET.widthMax);let err=null;if(shown&&(reference==='target'||ref)){err=new Float32Array(N);for(let p=0;p<N;p++)for(let c=0;c<3;c++)err[p]+=Math.abs(shown[c*N+p]-(reference==='target'?example.target[c*N+p]/255:ref[c*N+p]))/3}draw($(key+'-error'),err,'map',DATASET.errorMax);$(key+'-errorLabel').textContent=reference==='target'?'Absolute error':'Difference vs '+M.find(v=>v[0]===reference)[1];let v=m.metrics;$(key+'-metrics').innerHTML=`<div><span>Reconstruction PSNR ↑</span><strong>${v.psnr.toFixed(3)} dB</strong></div><div><span>Reconstruction SSIM ↑</span><strong>${v.ssim.toPrecision(5)}</strong></div><div><span>90% interval coverage</span><strong>${(v.coverage*100).toFixed(2)}%</strong></div><div><span>Mean width ↓</span><strong>${v.width.toFixed(5)}</strong></div>`;for(let j=0;j<5;j++){draw($(key+'-q'+j),quantileImage(key,j),'float');$(key+'-qLabel'+j).textContent=key==='fixed'?($('approx').checked?'Assumed linear interpolation':'Not available from this head'):'q = '+DATASET.quantiles[j].toFixed(2)}}inspect()}
function pick(x,y){point={x:Math.max(0,Math.min(255,Math.round(x))),y:Math.max(0,Math.min(255,Math.round(y)))};$('px').value=point.x;$('py').value=point.y;render()}
function inspect(){if(!example)return;const p=point.y*256+point.x,c=Number($('channel').value),idx=c*N+p,t=example.target[idx]/255,levels=DATASET.quantiles,series=[];let warnings=[];
$('pixelTitle').textContent=`Pixel (${point.x}, ${point.y}) · ${['Red','Green','Blue'][c]} channel`;
$('quantileRows').innerHTML=M.map(([key,label,col])=>{const m=example.models[key];let vals=null;if(key==='fixed'){if($('approx').checked){let lo=m.endpoints[idx],hi=m.endpoints[3*N+idx];vals=levels.map(q=>lo+(hi-lo)*(q-.025)/.95)}}else vals=levels.map((q,j)=>m.q[j*3*N+idx]);if(vals){series.push({key,label,col,vals});if(vals.some((v,j)=>j&&v<vals[j-1]))warnings.push(label+' has crossing quantiles at this pixel.')}return `<tr><td style="color:${col}">${label}${key==='fixed'&&vals?'*':''}</td>${levels.map((q,j)=>`<td>${vals?vals[j].toFixed(4):'—'}</td>`).join('')}</tr>`}).join('');
let ep=example.models.fixed.endpoints;$('endpoints').textContent=`Native fixed-head endpoints: q .025 = ${ep[idx].toFixed(4)}; q .975 = ${ep[3*N+idx].toFixed(4)}. ${$('approx').checked?'* Five values above are assumed linear interpolation.':'Enable the interpolation option to see an assumed curve.'}`;
$('truth').textContent=`Ground truth: ${t.toFixed(4)} · Measurement: ${(example.measurement[idx]/255).toFixed(4)} · intensity units [0,1]`;
$('crossing').textContent=warnings.join(' ');let all=series.flatMap(s=>s.vals).concat(t),low=Math.min(...all),high=Math.max(...all),pad=Math.max(.015,(high-low)*.15);low-=pad;high+=pad;let x=v=>60+(v-low)/(high-low)*570,y=q=>260-q*220;
let svg=`<rect width="660" height="310" fill="transparent"/>`;
for(let j=0;j<=4;j++){let v=low+(high-low)*j/4;svg+=`<line x1="${x(v)}" y1="30" x2="${x(v)}" y2="260" stroke="#293443"/><text x="${x(v)}" y="283" fill="#a0aec0" font-size="12" text-anchor="middle">${v.toFixed(3)}</text>`}
for(let q of levels)svg+=`<line x1="60" y1="${y(q)}" x2="630" y2="${y(q)}" stroke="#293443"/><text x="48" y="${y(q)+4}" fill="#a0aec0" font-size="12" text-anchor="end">${q.toFixed(2)}</text>`;
svg+=`<text x="60" y="17" fill="#a0aec0" font-size="12">Quantile level q</text><text x="345" y="307" fill="#a0aec0" font-size="12" text-anchor="middle">Predicted pixel intensity</text><line x1="${x(t)}" y1="30" x2="${x(t)}" y2="260" stroke="white" stroke-dasharray="3 5"/>`;
for(const s of series){svg+=`<polyline points="${s.vals.map((v,j)=>`${x(v)},${y(levels[j])}`).join(' ')}" fill="none" stroke="${s.col}" stroke-width="2" ${s.key==='fixed'?'stroke-dasharray="6 5"':''}/>`;for(let j=0;j<5;j++)svg+=`<circle cx="${x(s.vals[j])}" cy="${y(levels[j])}" r="4" fill="${s.col}"/>`}$('chart').innerHTML=svg;$('legend').innerHTML=series.map(s=>`<span style="color:${s.col}">● ${s.label}${s.key==='fixed'?' (assumed)':''}</span>`).join('')+'<span>┊ Ground truth</span>';if($('pixelDialog').open)renderPixelDetail()}
function rgbAt(a,p){return [0,1,2].map(c=>a[c*N+p])}
function rgbCSS(v){return 'rgb('+v.map(x=>Math.round(Math.max(0,Math.min(1,x))*255)).join(',')+')'}
function openPixelDetail(source){const match=source.match(/-q([0-4])$/);if(match)$('quantileStep').value=match[1];else if($('imageMode').value!=='mean')$('quantileStep').value=$('imageMode').value;if(!$('pixelDialog').open)$('pixelDialog').showModal();renderPixelDetail()}
function renderPixelDetail(){if(!example)return;const p=point.y*256+point.x,j=Number($('quantileStep').value);$('detailTitle').textContent=`Image ${example.id} · pixel (${point.x}, ${point.y})`;$('stepLabel').textContent='q = '+DATASET.quantiles[j].toFixed(2);$('detailX').value=point.x;$('detailY').value=point.y;$('detailApprox').checked=$('approx').checked;const gt=[0,1,2].map(c=>example.target[c*N+p]/255);$('detailTruth').innerHTML=`Ground truth <span class="detail-truth-swatch" style="background:${rgbCSS(gt)}"></span> RGB (${gt.map(v=>v.toFixed(5)).join(', ')})`;
$('pixelStrip').innerHTML='<div></div>'+DATASET.quantiles.map(q=>`<div class="strip-heading">q = ${q.toFixed(2)}</div>`).join('')+M.map(([k,label,col])=>`<div class="strip-name" style="color:${col}">${label}${k==='fixed'&&$('approx').checked?'<br><small>Assumed interpolation</small>':''}</div>`+DATASET.quantiles.map((q,n)=>`<div class="strip-cell ${n===j?'active':''}" id="strip-${k}-${n}"></div>`).join('')).join('');
for(const [k]of M)for(let n=0;n<5;n++){const cell=$(`strip-${k}-${n}`),a=quantileImage(k,n);if(!a){cell.innerHTML='<div class="strip-na">Not learned<br>Native q .025 / .975</div>';continue}const rgb=rgbAt(a,p);cell.innerHTML=`<canvas width="170" height="170" aria-label="${k} neighborhood at q ${DATASET.quantiles[n]}"></canvas><span class="pixel-swatch" style="background:${rgbCSS(rgb)}"></span><span class="small">Pixel</span><div class="strip-rgb">R ${rgb[0].toFixed(5)}<br>G ${rgb[1].toFixed(5)}<br>B ${rgb[2].toFixed(5)}</div>`;const cv=cell.querySelector('canvas'),ctx=cv.getContext('2d'),ox=Math.max(0,Math.min(239,point.x-8)),oy=Math.max(0,Math.min(239,point.y-8));for(let dy=0;dy<17;dy++)for(let dx=0;dx<17;dx++){ctx.fillStyle=rgbCSS(rgbAt(a,(oy+dy)*256+ox+dx));ctx.fillRect(dx*10,dy*10,10,10)}ctx.strokeStyle='black';ctx.lineWidth=3;ctx.strokeRect((point.x-ox)*10,(point.y-oy)*10,10,10);ctx.strokeStyle='white';ctx.lineWidth=1;ctx.strokeRect((point.x-ox)*10,(point.y-oy)*10,10,10)}}
function boot(){if(!window.DATASET){$('status').textContent='Dataset missing: place the supplied data folder beside this page.';return}$('example').innerHTML=DATASET.ids.map((id,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} · image ${id}</option>`).join('');$('cards').innerHTML=M.map(([k,l,col,sub])=>`<article class="card"><h2 style="color:${col}">${l}</h2><p class="subtitle">${sub}</p><div class="views">${[['prediction','Reconstruction'],['width','Uncertainty · 90% width'],['error','Absolute error']].map(([v,label])=>`<figure><canvas tabindex="0" id="${k}-${v}" width="256" height="256" aria-label="${l}: ${label}. Click to select pixel; arrow keys move selection."></canvas><figcaption id="${k}-${v==='prediction'?'imageLabel':v==='error'?'errorLabel':'widthLabel'}">${label}</figcaption></figure>`).join('')}</div><div class="metrics" id="${k}-metrics"></div></article>`).join('');$('scales').textContent=`Width: 0–${DATASET.widthMax.toFixed(3)} · Error: 0–${DATASET.errorMax.toFixed(3)}`;
$('quantileGallery').innerHTML='<div></div>'+M.map(([k,l,col])=>`<div class="q-heading" style="color:${col}">${l}</div>`).join('')+DATASET.quantiles.map((q,j)=>`<div class="q-label">q ${q.toFixed(2)}</div>`+M.map(([k,l])=>`<figure><canvas tabindex="0" id="${k}-q${j}" width="256" height="256" aria-label="${l} image at quantile ${q}"></canvas><figcaption id="${k}-qLabel${j}"></figcaption></figure>`).join('')).join('');for(const cv of document.querySelectorAll('canvas')){cv.addEventListener('click',e=>{if(busy)return;const b=cv.getBoundingClientRect();pick(Math.floor(Number(cv.dataset.ox||0)+(e.clientX-b.left)/b.width*Number(cv.dataset.size||256)),Math.floor(Number(cv.dataset.oy||0)+(e.clientY-b.top)/b.height*Number(cv.dataset.size||256)));openPixelDetail(cv.id)});cv.addEventListener('keydown',e=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();pick(point.x+delta[0],point.y+delta[1])}})}$('example').onchange=e=>load(Number(e.target.value));$('next').onclick=()=>load((current+1)%DATASET.count);$('previous').onclick=()=>load((current+DATASET.count-1)%DATASET.count);$('random').onclick=()=>load((current+1+Math.floor(Math.random()*(DATASET.count-1)))%DATASET.count);$('channel').onchange=inspect;$('approx').onchange=render;for(const id of ['imageMode','zoom','difference'])$(id).onchange=render;for(const id of ['px','py'])$(id).onchange=()=>pick(Number($('px').value)||0,Number($('py').value)||0);$('closePixel').onclick=()=>$('pixelDialog').close();$('pixelDialog').addEventListener('click',e=>{if(e.target===$('pixelDialog')){const b=$('pixelDialog').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('pixelDialog').close()}});$('quantileStep').oninput=()=>{$('imageMode').value=$('quantileStep').value;render()};$('detailApprox').onchange=()=>{$('approx').checked=$('detailApprox').checked;render()};for(const id of ['detailX','detailY'])$(id).onchange=()=>pick(Number($('detailX').value)||0,Number($('detailY').value)||0);load(0)}boot();
